services:
    minio-nginx:
        container_name: minio-nginx
        restart: unless-stopped
        image: nginx:${NGINX_VERSION}
        volumes:
            - ./nginx/${VHOST_FILE}:/etc/nginx/conf.d/custom.conf
        ports:
            - "80"
        depends_on:
            - minio-minio1
            - minio-minio2
            - minio-minio3
            - minio-minio4
        environment:
            VIRTUAL_HOST: ${DOMAIN_HOST}
            SELF_SIGNED_HOST: ${SELF_SIGNED_HOST}
            VIRTUAL_PORT: 80
            LETSENCRYPT_HOST: ${DOMAIN_HOST}
            LETSENCRYPT_EMAIL: ${DOMAIN_EMAIL}
        networks:
            - nginx-proxy
            - minio

    minio-minio1:
        container_name: minio-minio1
        image: minio/minio:${MINIO_VERSION}
        restart: unless-stopped
        volumes:
            - ../data1:/data
        environment:
            MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
            MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
        networks:
            - minio
        command: server http://minio-minio{1...4}/data --console-address ":9001"
    minio-minio2:
        container_name: minio-minio2
        image: minio/minio:${MINIO_VERSION}
        restart: unless-stopped
        volumes:
            - ../data2:/data
        environment:
            MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
            MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
        networks:
            - minio
        command: server http://minio-minio{1...4}/data --console-address ":9001"
    minio-minio3:
        container_name: minio-minio3
        image: minio/minio:${MINIO_VERSION}
        restart: unless-stopped
        volumes:
            - ../data3:/data
        environment:
            MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
            MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
        networks:
            - minio
        command: server http://minio-minio{1...4}/data --console-address ":9001"
    minio-minio4:
        container_name: minio-minio4
        image: minio/minio:${MINIO_VERSION}
        restart: unless-stopped
        volumes:
            - ../data4:/data
        environment:
            MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
            MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
        networks:
            - minio
        command: server http://minio-minio{1...4}/data --console-address ":9001"

networks:
    minio:
    nginx-proxy:
        external: true
